CREATE TABLE sessions (
    id TEXT PRIMARY KEY NOT NULL UNIQUE,
    user_id INTEGER NOT NULL,
    session_token TEXT NOT NULL UNIQUE,
    csrf_token TEXT NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

