CREATE TABLE IF NOT EXISTS post_visibility (
    id TEXT PRIMARY KEY NOT NULL UNIQUE,
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);