'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/context/AuthContext';
import RegisterForm from '@/components/auth/RegisterForm';

export default function RegisterPage() {
  const router = useRouter();
  const { toast } = useToast();
  const { register } = useAuth();
  const [isLoading, setIsLoading] = useState(false);

  const handleRegister = async (formData) => {
    setIsLoading(true);
  
    try {
      // Log the registration data
      console.log('Registering with data:', formData);
      
      // Create a user object from form data (for frontend use)
      let avatarUrl = '';
      
      // Only try to create object URL if avatar is a valid File object
      if (formData.avatar && formData.avatar instanceof File) {
        try {
          avatarUrl = URL.createObjectURL(formData.avatar);
        } catch (error) {
          console.error('Error creating avatar URL:', error);
          // Continue without avatar if there's an error
        }
      }
      
      // Prepare user data for frontend display
      const userData = {
        id: '1', // This will be generated by the backend in a real scenario
        firstName: formData.first_name,
        lastName: formData.last_name,
        email: formData.email,
        nickname: formData.nickname || formData.email.split('@')[0],
        date_of_birth: formData.date_of_birth,
        about_me: formData.about || '',
        avatar: avatarUrl,
        is_public: formData.is_public
      };
      
      // Try to send registration data to backend API
      let backendSuccess = false;
      let backendError = null;
      
      try {
        // Carefully format the data for the backend API
        const apiFormData = {};
        
        // Required fields
        apiFormData.email = formData.email;
        apiFormData.password = formData.password;
        apiFormData.confirmed_password = formData.confirmed_password;
        apiFormData.first_name = formData.first_name;
        apiFormData.last_name = formData.last_name;
        apiFormData.date_of_birth = formData.date_of_birth; // Pass date as is, API route will format it
        
        // Optional fields
        apiFormData.nickname = formData.nickname || '';
        apiFormData.about_me = formData.about || '';
        apiFormData.is_public = formData.is_public !== undefined ? formData.is_public : true;
        
        // Skip avatar for API call as it's a File object that can't be serialized
        
        console.log('Sending to backend API:', apiFormData);
        
        console.log('Note: Ensure backend server is running on port 8000');
        const response = await fetch('/api/auth/register', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(apiFormData),
          // Set a timeout to prevent waiting too long
          signal: AbortSignal.timeout(5000) // 5 second timeout
        });
        
        const result = await response.json();
        
        if (response.ok && result.success) {
          backendSuccess = true;
          console.log('Backend registration successful:', result);
        } else {
          backendError = result.error || `Backend error: ${response.status}`;
          console.warn('Backend registration issue:', backendError);
        }
      } catch (error) {
        // If backend is unavailable, log error but continue with frontend mock
        backendError = error.message || 'Failed to connect to backend';
        console.warn('Backend connection failed:', backendError);
      }
      register(userData);
  
      // Show appropriate toast message based on backend success
      if (backendSuccess) {
        toast({
          title: "Account created",
          description: "Your account has been created successfully and data stored in the backend",
        });
      } else {
        // Still show success, but note that only frontend data is available
        toast({
          title: "Account created (Frontend only)",
          description: backendError 
            ? `Frontend account created, but backend storage failed: ${backendError}` 
            : "Your account has been created in the frontend only. Backend storage unavailable.",
          variant: "warning"
        });
        
        // Log the issue for debugging
        console.log('Registration continued with frontend mock data only due to backend issue.');
      }
      
      // Redirect to the home page
      router.push('/');
    } catch (error) {
      console.error('Registration error:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to create account",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };
  
  return (
    <div className="w-full max-w-md space-y-6 bg-white rounded-lg p-6">
      <div className="text-center">
        <h1 className="text-2xl font-bold">Create an Account</h1>
        <p className="text-gray-500 mt-2">Enter your information to register</p>
      </div>

      <RegisterForm onSubmit={handleRegister} isLoading={isLoading} />

      <div className="text-center text-sm">
        <p>
          Already have an account?{' '}
          <Link href="/login" className="text-blue-600 hover:underline">
            Login here
          </Link>
        </p>
      </div>
    </div>
  );
}
