'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/context/AuthContext';
import RegisterForm from '@/components/auth/RegisterForm';

export default function RegisterPage() {
  const router = useRouter();
  const { toast } = useToast();
  const { register } = useAuth();
  const [isLoading, setIsLoading] = useState(false);

  const handleRegister = async (formData) => {
    setIsLoading(true);
  
    try {
      // Log the registration data
      console.log('Registering with data:', formData);
      
      // Create a user object from form data
      let avatarUrl = '';
      
      // Only try to create object URL if avatar is a valid File object
      if (formData.avatar && formData.avatar instanceof File) {
        try {
          avatarUrl = URL.createObjectURL(formData.avatar);
        } catch (error) {
          console.error('Error creating avatar URL:', error);
          // Continue without avatar if there's an error
        }
      }
      
      const userData = {
        id: '1', // In a real app, this would be generated by the backend
        firstName: formData.first_name,
        lastName: formData.last_name,
        email: formData.email,
        nickname: formData.nickname || formData.email.split('@')[0],
        date_of_birth: formData.date_of_birth,
        about_me: formData.about || '',
        avatar: avatarUrl,
        is_public: formData.is_public
      };
      
      // Use register function from AuthContext to set user data and cookies
      register(userData);
  
      toast({
        title: "Account created",
        description: "Your account has been created successfully",
      });
      
      // Redirect to the home page
      router.push('/');
    } catch (error) {
      console.error('Registration error:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to create account",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };
  
  return (
    <div className="w-full max-w-md space-y-6 bg-white rounded-lg p-6">
      <div className="text-center">
        <h1 className="text-2xl font-bold">Create an Account</h1>
        <p className="text-gray-500 mt-2">Enter your information to register</p>
      </div>

      <RegisterForm onSubmit={handleRegister} isLoading={isLoading} />

      <div className="text-center text-sm">
        <p>
          Already have an account?{' '}
          <Link href="/login" className="text-blue-600 hover:underline">
            Login here
          </Link>
        </p>
      </div>
    </div>
  );
}
